services:
    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        hostname: docker-rabbitmq        
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./home/dri/Projetos/rabbitdata:/var/lib/rabbitmq/mnesia
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest